version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile_php_apache
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
      - ./:/var/www/html/
    tty: true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4.21
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./db/:/var/lib/mysql/
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: example
